base_url = "https://montekki.github.io"

compile_sass = true

build_search_index = false

title = ""

theme = "tale-zola"

taxonomies = [
    { name = "tags" },
]

[markdown]
highlight_code = true 
highlight_theme = "base16-atelierdune-light"

[extra]
author = "Fedor Sakharov"
katex = true

[[extra.menu]]
name = "Blog"
url = ""

[[extra.menu]]
name = "Tags"
url = "tags"

[[extra.menu]]
name = "About"
url = "about"

[extra.footer]
start_year = "2022"
end_year = "2022"
info = ""
