base_url = "https://montekki.github.io"

compile_sass = true

generate_feeds = true

build_search_index = false

title = ""

theme = "tale-zola"

taxonomies = [
    { name = "tags" },
]

[markdown]
highlight_code = true 
highlight_theme = "base16-atelierdune-light"

[extra]
author = "Fedor Sakharov"
github = "https://github.com/montekki"
email = "fedor.sakharov@gmail.com"
katex = true

[[extra.menu]]
name = "Blog"
url = ""

[[extra.menu]]
name = "Tags"
url = "tags"

[[extra.menu]]
name = "About"
url = "about"

[extra.seo]
image = "assets/favicon.jpg"
image_height = 0 
image_width = 0
og_locale = "en_US"

[extra.seo.twitter]
site = "m0nt3kk1"
creator = "m0nt3kk1"

[extra.footer]
start_year = "2022"
end_year = "2024"
info = ""
